packages:
  - apps/*

catalog:
  '@biomejs/biome': 1.9.4
  typescript: ~5.8.3

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': ^18.3.3
    '@types/react-dom': ^18.3.0
  react-native:
    react: 19.0.0
    react-dom: 19.0.0
    react-native: 0.79.0
    '@types/react': ~19.0.10

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@biomejs/biome'
