import {
	Alert,
	Meal,
	MealPrepSummary,
	Period,
	AlertType,
	StatItem,
} from "./types";

// Prep summary with English/Arabic
export const TODAY_PREP_SUMMARY: MealPrepSummary[] = [
	{
		period: "Breakfast" as Period,
		totalMeals: 25,
		mealsToPrep: [
			{ id: "shashuka", name: "Shashuka", name_ar: "شكشوكة", count: 15 },
			{ id: "oats", name: "Overnight Oats", name_ar: "شوفان مبيت", count: 7 },
			{
				id: "smoothie",
				name: "Green Smoothie",
				name_ar: "عصير أخضر",
				count: 3,
			},
		],
	},
	{
		period: "Lunch" as Period,
		totalMeals: 32,
		mealsToPrep: [
			{
				id: "salad_x",
				name: "Quinoa Salad",
				name_ar: "سلطة الكينوا",
				count: 18,
			},
			{
				id: "wrap_y",
				name: "Falafel Wrap",
				name_ar: "لفائف الفلافل",
				count: 10,
			},
			{ id: "soup_z", name: "Lentil Soup", name_ar: "حساء العدس", count: 4 },
			{ id: "extra1", name: "Side Salad", name_ar: "سلطة جانبية", count: 2 },
		],
	},
	{
		period: "Dinner" as Period,
		totalMeals: 28,
		mealsToPrep: [
			{
				id: "salmon",
				name: "Grilled Salmon",
				name_ar: "سلمون مشوي",
				count: 12,
			},
			{
				id: "tofu_stirfry",
				name: "Tofu Stir-fry",
				name_ar: "توفو مقلي",
				count: 9,
			},
			{
				id: "pasta_veg",
				name: "Veggie Pasta",
				name_ar: "باستا بالخضار",
				count: 7,
			},
		],
	},
];

// Alerts with English/Arabic
export const ALERTS: Alert[] = [
	{
		id: "1",
		type: "info" as AlertType,
		title: "New 'Keto Weekly' subscriber",
		title_ar: "مشترك جديد في 'كيتو الأسبوعية'",
		icon: "person-add-outline",
		timestamp: "3h ago",
		message: "A new customer has subscribed to your Keto Weekly meal plan",
		message_ar: "اشترك عميل جديد في خطة وجبات كيتو الأسبوعية الخاصة بك",
	},
	{
		id: "2",
		type: "warning" as AlertType,
		title: "Low inventory: Quinoa",
		title_ar: "مخزون منخفض: الكينوا",
		icon: "cube-outline",
		timestamp: "1h ago",
		message: "Quinoa inventory is below minimum threshold (2kg remaining)",
		message_ar: "مخزون الكينوا أقل من الحد الأدنى (٢ كجم متبقي)",
	},
	{
		id: "3",
		type: "error" as AlertType,
		title: "Delivery issue Order #12345",
		title_ar: "مشكلة في التوصيل للطلب #12345",
		icon: "car-sport-outline",
		timestamp: "Yesterday",
		message: "Delivery for Order #12345 was marked as incomplete by customer",
		message_ar: "تم تحديد التوصيل للطلب #12345 كغير مكتمل من قبل العميل",
	},
	{
		id: "4",
		type: "success" as AlertType,
		title: "Weekly revenue goal reached",
		title_ar: "تم الوصول إلى هدف الإيرادات الأسبوعي",
		icon: "trending-up-outline",
		timestamp: "Today",
		message:
			"Congratulations! You've reached your weekly revenue target of $5,000",
		message_ar:
			"تهانينا! لقد وصلت إلى هدف الإيرادات الأسبوعي البالغ 5,000 دولار",
	},
	{
		id: "5",
		type: "info" as AlertType,
		title: "Staff meeting reminder",
		title_ar: "تذكير باجتماع الموظفين",
		icon: "calendar-outline",
		timestamp: "Tomorrow",
		message: "Reminder: Staff meeting scheduled for tomorrow at 9:00 AM",
		message_ar: "تذكير: اجتماع الموظفين مقرر غدا الساعة 9:00 صباحا",
	},
];

// Dashboard stats with English/Arabic
export const DASHBOARD_STATS: StatItem[] = [
	{
		title: "Active Subscriptions",
		title_ar: "الاشتراكات النشطة",
		value: 87,
		icon: "people-outline",
		change: 12,
		changeDirection: "up",
	},
	{
		title: "Today's Orders",
		title_ar: "طلبات اليوم",
		value: 23,
		icon: "restaurant-outline",
		change: 4,
		changeDirection: "up",
	},
	{
		title: "Weekly Revenue",
		title_ar: "الإيرادات الأسبوعية",
		value: "$4,235",
		icon: "cash-outline",
		change: 7.5,
		changeDirection: "up",
	},
	{
		title: "Inventory Items",
		title_ar: "عناصر المخزون",
		value: 145,
		icon: "cube-outline",
		change: 2,
		changeDirection: "down",
	},
];

// Meals with complete English/Arabic and doubled quantity
export const MEALS: Meal[] = [
	// BREAKFAST MEALS
	{
		featured: false,
		isVegan: false,
		id: "b1",
		name: "Shakshuka",
		name_ar: "شكشوكة",
		description: "Eggs poached in spiced tomato sauce",
		description_ar: "بيض مطبوخ في صلصة طماطم متبلة",
		price: 12.99,
		calories: 380,
		prepTime: 25,
		period: "Breakfast" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=800",
		nutritionalInfo: {
			protein: 14,
			carbs: 20,
			fat: 25,
			sugar: 5,
			sodium: 400,
		},
		tags: ["breakfast", "protein", "vegetarian"],
		dietaryRestriction: "vegetarian",
	},
	{
		featured: true,
		isVegan: true,
		id: "b2",
		name: "Overnight Oats",
		name_ar: "شوفان مبيت",
		description: "Oats soaked with yogurt and fruits",
		description_ar: "شوفان منقوع مع الزبادي والفواكه",
		price: 8.99,
		calories: 320,
		prepTime: 10,
		period: "Breakfast" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1614961233913-a5113a4a34ed?w=800",
		nutritionalInfo: {
			protein: 12,
			carbs: 45,
			fat: 8,
			sugar: 15,
			sodium: 120,
		},
		tags: ["breakfast", "vegan", "dairy-free"],
		dietaryRestriction: "vegan",
	},
	{
		featured: true,
		isVegan: true,
		id: "b3",
		name: "Green Smoothie Bowl",
		name_ar: "وعاء العصير الأخضر",
		description: "Nutrient-packed smoothie with fresh fruits and superfoods",
		description_ar: "عصير مليء بالعناصر الغذائية مع الفواكه الطازجة",
		price: 10.99,
		calories: 290,
		prepTime: 15,
		period: "Breakfast" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1638176066666-ffee9577c6d9?w=800",
		nutritionalInfo: {
			protein: 10,
			carbs: 42,
			fat: 7,
			sugar: 18,
			sodium: 85,
		},
		tags: ["breakfast", "vegan", "gluten-free"],
		dietaryRestriction: "vegan",
	},
	{
		featured: false,
		isVegan: false,
		id: "b4",
		name: "Protein Pancakes",
		name_ar: "بانكيك بروتين",
		description: "Fluffy pancakes with added protein and topped with berries",
		description_ar: "بانكيك رقيق مع إضافة البروتين ومغطى بالتوت",
		price: 11.5,
		calories: 420,
		prepTime: 20,
		period: "Breakfast" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800",
		nutritionalInfo: {
			protein: 24,
			carbs: 48,
			fat: 12,
			sugar: 8,
			sodium: 220,
		},
		tags: ["breakfast", "protein", "high-protein"],
		dietaryRestriction: "none",
	},
	{
		featured: true,
		isVegan: false,
		id: "b5",
		name: "Greek Yogurt Bowl",
		name_ar: "وعاء الزبادي اليوناني",
		description: "Greek yogurt with honey, nuts, and fresh berries",
		description_ar: "زبادي يوناني مع العسل والمكسرات والتوت الطازج",
		price: 9.75,
		calories: 310,
		prepTime: 8,
		period: "Breakfast" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?w=800",
		nutritionalInfo: {
			protein: 18,
			carbs: 32,
			fat: 14,
			sugar: 22,
			sodium: 95,
		},
		tags: ["breakfast", "protein", "gluten-free"],
		dietaryRestriction: "vegetarian",
	},
	{
		featured: false,
		isVegan: false,
		id: "b6",
		name: "Avocado Toast",
		name_ar: "توست الأفوكادو",
		description: "Sourdough toast topped with smashed avocado and poached egg",
		description_ar: "توست مخمر مغطى بالأفوكادو المهروس والبيض المسلوق",
		price: 12.5,
		calories: 350,
		prepTime: 12,
		period: "Breakfast" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1603046891744-76e6300f82ef?w=800",
		nutritionalInfo: {
			protein: 14,
			carbs: 28,
			fat: 22,
			sugar: 2,
			sodium: 280,
		},
		tags: ["breakfast", "vegetarian", "toast"],
		dietaryRestriction: "vegetarian",
	},

	// LUNCH MEALS
	{
		featured: false,
		isVegan: false,
		id: "l1",
		name: "Quinoa Salad",
		name_ar: "سلطة الكينوا",
		description: "Fresh salad with quinoa and vegetables",
		description_ar: "سلطة طازجة مع الكينوا والخضروات",
		price: 14.99,
		calories: 420,
		prepTime: 20,
		period: "Lunch" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800",
		nutritionalInfo: {
			protein: 15,
			carbs: 35,
			fat: 18,
			sugar: 4,
			sodium: 320,
		},
		tags: ["lunch", "gluten-free", "vegan"],
		dietaryRestriction: "vegan",
	},
	{
		featured: true,
		isVegan: true,
		id: "l2",
		name: "Falafel Wrap",
		name_ar: "لفائف الفلافل",
		description: "Falafel with vegetables in a whole wheat wrap",
		description_ar: "فلافل مع الخضروات في خبز القمح الكامل",
		price: 10.99,
		calories: 480,
		prepTime: 15,
		period: "Lunch" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
		nutritionalInfo: {
			protein: 18,
			carbs: 55,
			fat: 12,
			sugar: 3,
			sodium: 450,
		},
		tags: ["lunch", "vegan", "plant-based"],
		dietaryRestriction: "vegan",
	},
	{
		featured: true,
		isVegan: false,
		id: "l3",
		name: "Mediterranean Bowl",
		name_ar: "وعاء البحر الأبيض المتوسط",
		description:
			"Mediterranean-inspired protein bowl with hummus and grilled chicken",
		description_ar:
			"وعاء بروتين مستوحى من البحر الأبيض المتوسط مع الحمص والدجاج المشوي",
		price: 13.5,
		calories: 510,
		prepTime: 25,
		period: "Lunch" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
		nutritionalInfo: {
			protein: 35,
			carbs: 38,
			fat: 22,
			sugar: 5,
			sodium: 680,
		},
		tags: ["lunch", "protein", "mediterranean"],
		dietaryRestriction: "none",
	},
	{
		featured: false,
		isVegan: false,
		id: "l4",
		name: "Lentil Soup",
		name_ar: "حساء العدس",
		description: "Hearty lentil soup with vegetables and spices",
		description_ar: "حساء عدس دسم مع الخضروات والتوابل",
		price: 8.99,
		calories: 280,
		prepTime: 30,
		period: "Lunch" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
		nutritionalInfo: {
			protein: 16,
			carbs: 40,
			fat: 6,
			sugar: 4,
			sodium: 580,
		},
		tags: ["lunch", "soup", "vegan"],
		dietaryRestriction: "vegan",
	},
	{
		featured: true,
		isVegan: false,
		id: "l5",
		name: "Chicken Caesar Salad",
		name_ar: "سلطة سيزر بالدجاج",
		description: "Classic Caesar salad with grilled chicken breast",
		description_ar: "سلطة سيزر كلاسيكية مع صدر دجاج مشوي",
		price: 12.5,
		calories: 420,
		prepTime: 15,
		period: "Lunch" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800",
		nutritionalInfo: {
			protein: 32,
			carbs: 12,
			fat: 28,
			sugar: 3,
			sodium: 680,
		},
		tags: ["lunch", "protein", "salad"],
		dietaryRestriction: "none",
	},
	{
		featured: false,
		isVegan: true,
		id: "l6",
		name: "Buddha Bowl",
		name_ar: "وعاء بوذا",
		description:
			"Nutritious bowl with rice, roasted vegetables and tahini dressing",
		description_ar: "وعاء مغذي مع الأرز والخضروات المحمصة وصلصة الطحينة",
		price: 13.99,
		calories: 450,
		prepTime: 20,
		period: "Lunch" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=800",
		nutritionalInfo: {
			protein: 14,
			carbs: 62,
			fat: 16,
			sugar: 8,
			sodium: 340,
		},
		tags: ["lunch", "vegan", "bowl"],
		dietaryRestriction: "vegan",
	},

	// DINNER MEALS
	{
		featured: false,
		isVegan: false,
		id: "d1",
		name: "Grilled Salmon",
		name_ar: "سلمون مشوي",
		description: "Fresh salmon with herbs and lemon",
		description_ar: "سلمون طازج مع الأعشاب والليمون",
		price: 18.99,
		calories: 520,
		prepTime: 30,
		period: "Dinner" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800",
		nutritionalInfo: {
			protein: 42,
			carbs: 5,
			fat: 28,
			sugar: 1,
			sodium: 380,
		},
		tags: ["dinner", "protein", "omega-3"],
		dietaryRestriction: "none",
	},
	{
		featured: false,
		isVegan: true,
		id: "d2",
		name: "Tofu Stir-fry",
		name_ar: "توفو مقلي",
		description: "Tofu and vegetables in a savory sauce",
		description_ar: "توفو وخضروات في صلصة لذيذة",
		price: 13.99,
		calories: 380,
		prepTime: 25,
		period: "Dinner" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1512003867696-6d5ce6835040?w=800",
		nutritionalInfo: {
			protein: 22,
			carbs: 32,
			fat: 15,
			sugar: 8,
			sodium: 720,
		},
		tags: ["dinner", "vegan", "plant-based"],
		dietaryRestriction: "vegan",
	},
	{
		featured: true,
		isVegan: false,
		id: "d3",
		name: "Chicken Tikka Masala",
		name_ar: "دجاج تكا ماسالا",
		description:
			"Tender chicken in a rich and creamy tomato sauce with Indian spices",
		description_ar: "دجاج طري في صلصة طماطم غنية ودسمة مع توابل هندية",
		price: 16.99,
		calories: 590,
		prepTime: 35,
		period: "Dinner" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800",
		nutritionalInfo: {
			protein: 32,
			carbs: 25,
			fat: 36,
			sugar: 8,
			sodium: 820,
		},
		tags: ["dinner", "indian", "spicy"],
		dietaryRestriction: "none",
	},
	{
		featured: false,
		isVegan: false,
		id: "d4",
		name: "Herb-Crusted Lamb Chops",
		name_ar: "ريش الضأن بالأعشاب",
		description:
			"Premium lamb chops with a fragrant herb crust, served with roasted vegetables",
		description_ar:
			"ريش ضأن ممتازة مع قشرة عشبية عطرة، تقدم مع الخضروات المحمصة",
		price: 24.99,
		calories: 680,
		prepTime: 40,
		period: "Dinner" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1602057136788-8229ca596207?w=800",
		nutritionalInfo: {
			protein: 45,
			carbs: 22,
			fat: 42,
			sugar: 6,
			sodium: 540,
		},
		tags: ["dinner", "premium", "high-protein"],
		dietaryRestriction: "none",
	},
	{
		featured: true,
		isVegan: false,
		id: "d5",
		name: "Beef Stroganoff",
		name_ar: "بيف ستروغانوف",
		description: "Tender beef strips in a creamy mushroom sauce over pasta",
		description_ar: "شرائح لحم بقري طرية في صلصة كريمية بالفطر مع المعكرونة",
		price: 17.5,
		calories: 620,
		prepTime: 30,
		period: "Dinner" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=800",
		nutritionalInfo: {
			protein: 36,
			carbs: 48,
			fat: 32,
			sugar: 4,
			sodium: 720,
		},
		tags: ["dinner", "beef", "comfort-food"],
		dietaryRestriction: "none",
	},
	{
		featured: false,
		isVegan: true,
		id: "d6",
		name: "Vegan Mushroom Risotto",
		name_ar: "ريزوتو الفطر النباتي",
		description: "Creamy arborio rice with wild mushrooms and herbs",
		description_ar: "أرز أربوريو كريمي مع الفطر البري والأعشاب",
		price: 15.99,
		calories: 480,
		prepTime: 35,
		period: "Dinner" as Period,
		available: true,
		image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800",
		nutritionalInfo: {
			protein: 10,
			carbs: 78,
			fat: 16,
			sugar: 3,
			sodium: 420,
		},
		tags: ["dinner", "vegan", "italian"],
		dietaryRestriction: "vegan",
	},
];

// Top customers for reporting
export const TOP_CUSTOMERS = [
	{
		id: "c1",
		name: "Sarah Johnson",
		name_ar: "سارة جونسون",
		subscriptionType: "Premium Weekly",
		subscriptionType_ar: "أسبوعي ممتاز",
		totalSpent: 1245.5,
		orders: 24,
		joinDate: "2023-08-15",
	},
	{
		id: "c2",
		name: "Michael Chen",
		name_ar: "مايكل تشين",
		subscriptionType: "Family Plan",
		subscriptionType_ar: "خطة عائلية",
		totalSpent: 2390.75,
		orders: 32,
		joinDate: "2023-05-22",
	},
	{
		id: "c3",
		name: "Emma Rodriguez",
		name_ar: "إيما رودريغيز",
		subscriptionType: "Keto Plan",
		subscriptionType_ar: "خطة كيتو",
		totalSpent: 1876.25,
		orders: 28,
		joinDate: "2023-10-03",
	},
	{
		id: "c4",
		name: "David Williams",
		name_ar: "ديفيد ويليامز",
		subscriptionType: "Vegetarian",
		subscriptionType_ar: "نباتي",
		totalSpent: 1540.8,
		orders: 26,
		joinDate: "2023-07-19",
	},
	{
		id: "c5",
		name: "Olivia Thompson",
		name_ar: "أوليفيا طومسون",
		subscriptionType: "Premium Weekly",
		subscriptionType_ar: "أسبوعي ممتاز",
		totalSpent: 1190.45,
		orders: 21,
		joinDate: "2023-09-08",
	},
];
